-- Add flags to indicate if enrichment data was generated by an LLM
alter table words add column is_llm_pinyin boolean default false;
alter table words add column is_llm_translation boolean default false;
